### ISSUE TITLE
/pvp cannot be used again

### ISSUE THREAD

**Issue by lamya3** [LukeOnuke/pvp-toggle#10]
test environment here: #9 

## How
config.yml :
```
default-pvp: true
cooldown: 25
limited-time: 25
death-cooldown: -1
death-status: true
```
When `/pvp` be toggled first time, it seems to be works (turn pvp off by 25 sec then turn on) , but we can not use `/pvp` to switch it off again, it just keep it on.

**Comment by LukeOnuke** [comment]
Do the logs drop any exceptions?

**Comment by LukeOnuke** [comment]
Although I am still not an expert with this part of the code, maybe @MiningTcup could drop in.
> Have a sneaking suspition that its LeavesMC messing with apis.

Gonna look into it anyways too.

**Comment by MiningTcup** [comment]
Yea, any errors, and what exactly happens when you switch it again, does it say something? I'll try to replicate it.

**Comment by MiningTcup** [comment]
Could replicate. I believe I know the problem. Somewhere when toggling it uses default-pvp value, meaning that if default-pvp is true, this happens. I'll try to find it.

**Comment by MiningTcup** [comment]
public static boolean isPvpDisabled(Player player) {
        PersistentDataContainer dataContainer = player.getPersistentDataContainer();
        // Mr. Pier, this is a way of persistent storage of player states.
        return !defaultPvp.equals(dataContainer.get(isPvpEnabledKey, PersistentDataType.BOOLEAN));
    }

**Comment by MiningTcup** [comment]
There's the problem. This is the solution IntelliJ likes:
```Java
    public static boolean isPvpDisabled(Player player) {
        PersistentDataContainer dataContainer = player.getPersistentDataContainer();
        // Mr. Pier, this is a way of persistent storage of player states.
        return Boolean.FALSE.equals(dataContainer.get(isPvpEnabledKey, PersistentDataType.BOOLEAN));
    }
```

**Comment by MiningTcup** [comment]
I'm obviously not good with Git but it looks like this bug has always existed. I'll make a PR.

**Comment by MiningTcup** [comment]
nevermind that's broken too... give me a minute...

**Comment by MiningTcup** [comment]
this is severely scuffed

**Comment by MiningTcup** [comment]
Okay, making a PR
