### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by CTGamingPro** [LukeOnuke/pvp-toggle#2]
please make this available for 1.21

**Comment by LukeOnuke** [comment]
Not next to a reliable internet connection and a decent pc, comming like
this wednesday or thursday.

čet, 13. jun 2024. 23:43 CTGamingPro ***@***.***> је
написао/ла:

**Comment by LukeOnuke** [comment]
Gonna start work on it. Heard the APIs changed a lot, well see how long it takes

**Comment by LukeOnuke** [comment]
Made version v1.2.0a, it seems to work perfectly. I'll get it tested a bit more tmrw morning. 
If you could test it out with a friend or an alt, that would be amazing.

**Comment by CTGamingPro** [comment]
> Made version v1.2.0a, it seems to work perfectly. I'll get it tested a bit more tmrw morning. If you could test it out with a friend or an alt, that would be amazing.

nice hope to see it!

**Comment by LukeOnuke** [comment]
Well the full version is out
github: https://github.com/LukeOnuke/pvp-toggle/releases/tag/v1.2.0
modrinth: https://modrinth.com/plugin/pvp-toggle/version/1.2.0
