### ISSUE TITLE
PlaceholderAPI integration

### ISSUE THREAD

**Issue by davidkrammer** [LukeOnuke/pvp-toggle#5]
It would be beneficial to integrate the PlaceholderAPI into your plugin, so you can use it in e.g. a Scoreboard Plugin, to enable the display of “PVP: %pvp_status%” (PVP: ON /OFF).

This would provide players with constant awareness of whether they are currently engaged in player versus player (PVP) mode.

**Comment by LukeOnuke** [comment]
hopefully by this saturday this will be implemented

**Comment by LukeOnuke** [comment]
Added, will probably add more placeholders in the future.
