### ISSUE TITLE
Limited time protection function and customizable prompts ？

### ISSUE THREAD

**Issue by lamya3** [LukeOnuke/pvp-toggle#8]
Could we toggle pvp off by 120 sec ( even less or more? ), then turn it on automatically?

**Comment by MiningTcup** [comment]
Could you explain what you mean by customizable prompts? Do you mean, for example, "You are now Protected"?

**Comment by MiningTcup** [comment]
Done! I've added an option in the configuration (disabled by default) to make players vulnerable after a set number of seconds. I've also added config options for just about every message. It will take a little while for Luke to approve my changes, but for now you can compile it yourself using [my repo](https://github.com/MiningTcup/pvp-toggle). If you meant something else, please let me know!

**Comment by lamya3** [comment]
> Done! I've added an option in the configuration (disabled by default) to make players vulnerable after a set number of seconds. I've also added config options for just about every message. It will take a little while for Luke to approve my changes, but for now you can compile it yourself using [my repo](https://github.com/MiningTcup/pvp-toggle). If you meant something else, please let me know!

I'm sorry for the late reply, that's what I mean, and you did some great job! :D

**Comment by MiningTcup** [comment]
:D

**Comment by LukeOnuke** [comment]
Luke sadly has exams lmao, but miningtcup is realy at it. Got a final exam from cryptography this friday sooooo hopefully this evening imma look into both the pull requests and issues

**Comment by LukeOnuke** [comment]
As far as i understood @MiningTcup added all the stuffs.
